version: "3.9"

services:
  postgres-order:
    image: postgres:15
    container_name: postgres-order
    restart: always
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: orderuser
      POSTGRES_PASSWORD: orderpass
    ports:
      - "50011:5432"
    volumes:
      - api-order-service-v1-db-data:/var/lib/postgresql/data

  postgres-restaurant:
    image: postgres:15
    container_name: postgres-restaurant
    restart: always
    environment:
      POSTGRES_DB: restaurantdb
      POSTGRES_USER: restaurantuser
      POSTGRES_PASSWORD: restaurantpass
    ports:
      - "50031:5432"
    volumes:
      - api-restaurant-service-v1-db-data:/var/lib/postgresql/data

  postgres-delivery:
    image: postgres:15
    container_name: postgres-delivery
    restart: always
    environment:
      POSTGRES_DB: deliverydb
      POSTGRES_USER: deliveryuser
      POSTGRES_PASSWORD: deliverypass
    ports:
      - "50041:5432"
    volumes:
      - api-delivery-service-v1-db-data:/var/lib/postgresql/data

  postgres-payment:
    image: postgres:15
    container_name: postgres-payment
    restart: always
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: paymentuser
      POSTGRES_PASSWORD: paymentpass
    ports:
      - "50051:5432"
    volumes:
      - api-payment-service-v1-db-data:/var/lib/postgresql/data

volumes:
  api-order-service-v1-db-data:
  api-restaurant-service-v1-db-data:
  api-delivery-service-v1-db-data:
  api-payment-service-v1-db-data:
