server:
  port: 50020
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:50051/paymentdb
    username: paymentuser
    password: paymentpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # prod: create
    show-sql: true # comenta
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true # comenta
